//REST Client VSCode extension

GET  http://localhost:5000/tasks

###

POST http://localhost:5000/tasks
Content-Type: application/json

{
    "title": "Test API",
    "description": "",
    "points": 0,
    "status": "to-do",
    "deadline": null
}

###

DELETE http://localhost:5000/tasks/6303c79a93a90705edfa4e33

###

PATCH  http://localhost:5000/tasks/1234
Content-Type: application/json

{
    "title": "Changed Title"
}